Update .travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -50,7 +50,26 @@ before-script:
     EMU_PARAMS="-verbose -no-snapshot -no-window -gpu swiftshader_indirect -camera-back none -camera-front none -selinux permissive -qemu -m 2048"
     EMU_COMMAND="emulator"
     sudo -E sudo -u $USER -E bash -c "${ANDROID_HOME}/emulator/${EMU_COMMAND} -avd test ${AUDIO} ${EMU_PARAMS} &"
-  - $TOOLS/android-wait-for-emulator
+  - |
+    set +e
+    bootanim=""
+    failcounter=0
+    timeout_in_sec=600
+    until [[ "$bootanim" =~ "stopped" ]]; do
+      bootanim=`adb -e shell getprop init.svc.bootanim 2>&1 &`
+      if [[ "$bootanim" =~ "device not found" || "$bootanim" =~ "device offline"
+        || "$bootanim" =~ "running" || "$bootanim" =~  "error: no emulators found" ]]; then
+        let "failcounter += 1"
+        echo "Waiting for emulator to start"
+        if [[ $failcounter -gt timeout_in_sec ]]; then
+          echo "Timeout ($timeout_in_sec seconds) reached; failed to start emulator"
+          exit 1
+        fi
+      fi
+      sleep 1
+    done
+
+    echo "Emulator is ready"
   # - adb shell settings put global window_animation_scale 0 &
   # - adb shell settings put global transition_animation_scale 0 &
   # - adb shell settings put global animator_duration_scale 0 &
